### ISSUE TITLE
Migration to GitHub

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-packages/toric#1]
Thank you @wdjoyner for deciding to host package here. I have volunteered to help with further steps, and this is my to-do list:
- [x] merge two READMEs into one
- [x] check and update building manuals
- [x] add and check default tests
- [x] establish package website
- [x] update `PackageInfo.g`
- [x] publish new release.

**Comment by fingolfin** [comment]
The old website is offline, and the domain is now owned by a domain reseller :-(. So a new website would be able important for a new release.

I'd be happy to set one up using my tools, or explain again how to do it. It's less than 30 minutes work.

**Comment by olexandr-konovalov** [comment]
Thanks @fingolfin - I'd like to do this myself, to refresh my skills in using your tools (I've used them in the past, and apparently some updates happened since then). Maybe we can meet online at some point and try to do this together - should be less than 30 minutes ;). Of course, if you'd like to have Toric faster, please go ahead without me, I have a couple of more packages in my queue...

**Comment by fingolfin** [comment]
@wdjoyner the `PackageInfo.g` lists your homepage as http://opensourcemath.org/toric which is invalid. What shoudl we give as homepage instead? Or should it be left blank?

**Comment by wdjoyner** [comment]
On Wed, Feb 1, 2017 at 6:08 AM, Max Horn <notifications@github.com> wrote:

> @wdjoyner <https://github.com/wdjoyner> the PackageInfo.g lists your
> homepage as http://opensourcemath.org/toric which is invalid. What shoudl
> we give as homepage instead? Or should it be left blank?
>

I set a new page up here:
https://sites.google.com/site/wdjoyner/toric
The most recent version (with the bad command removed) isn't there yet
though.

**Comment by olexandr-konovalov** [comment]
@wdjoyner @fingolfin is the plan to migrate it to GitHub pages still in place?

**Comment by wdjoyner** [comment]
On Wed, Feb 1, 2017 at 7:37 AM, Alexander Konovalov <
notifications@github.com> wrote:

> @wdjoyner <https://github.com/wdjoyner> @fingolfin
> <https://github.com/fingolfin> is the plan to migrate it to GitHub pages
> still in place?
>

Yes, I think so. Maybe I misunderstand you though?

**Comment by olexandr-konovalov** [comment]
@wdjoyner no, it's fine then! Just to check, since you have mentioned the https://sites.google.com/site/wdjoyner/toric without saying that it is temporary.

**Comment by olexandr-konovalov** [comment]
@wdjoyner @fingolfin see version  1.9.0 at https://gap-packages.github.io/toric/. 

What is the license of the package - https://gap-packages.github.io/toric/doc/chap0.html mentions two :)

**Comment by wdjoyner** [comment]
On Thu, Feb 2, 2017 at 5:21 PM, Alexander Konovalov <
notifications@github.com> wrote:

> @wdjoyner <https://github.com/wdjoyner> @fingolfin
> <https://github.com/fingolfin> see version 1.9.0 at
> https://gap-packages.github.io/toric/.
>
> What is the license of the package - https://gap-packages.github.
> io/toric/doc/chap0.html mentions two :)
>

I think I deleted all mention of GPL in the latest xml file I emailed in.
MIT or modified BSD are both fine.

**Comment by olexandr-konovalov** [comment]
@wdjoyner I've just published Toric 1.9.1 with license information fixed. Please note it's now located in PackageInfo.g: https://github.com/gap-packages/toric/commit/8eb0d763b6089b79072e29f8befbcc12c2fe6a6c

**Comment by wdjoyner** [comment]
On Fri, Feb 3, 2017 at 10:42 AM, Alexander Konovalov <
notifications@github.com> wrote:

> @wdjoyner <https://github.com/wdjoyner> I've just published Toric 1.9.1
> with license information fixed. Please note it's now located in
> PackageInfo.g: 8eb0d76
> <https://github.com/gap-packages/toric/commit/8eb0d763b6089b79072e29f8befbcc12c2fe6a6c>
>

Many thanks Alexander!
