### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/toric#5]
There should be a `tst/testall.g` which runs tests -- e.g. `toric_examples.test` could be converted into one or several .tst files.

**Comment by olexandr-konovalov** [comment]
I can also add automated extraction of examples from the manual (one test file per chapter). 

Adding tests is actually a part of the checklist in #1.

**Comment by jgmbenoit** [comment]
The Debian package [gap-toric/1.8+ds-1](https://anonscm.debian.org/cgit/debian-science/packages/gap-toric.git) provides an ad hoc [tst/testall.g](https://anonscm.debian.org/cgit/debian-science/packages/gap-toric.git/tree/debian/adhoc/tst/testall.g) based on the document samples; the [extraction GAP script](https://anonscm.debian.org/cgit/debian-science/packages/gap-toric.git/tree/debian/adhoc/extract_examples.g) is also furnished. This approach is highly inspired by the machinery found the GAP package LAGUNA.

**Comment by fingolfin** [comment]
This has been resolved by 19efadb551dddf97bd31ca1bd1d332f83e2ba85f for now.

In the future, we may want to extract tests from the manual, but for now, the tests we have are a superset of the manual tests, with the exception of the example in issue #4.
