### ISSUE TITLE
Toric tests fail when all packages are loaded

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-packages/toric#7]
With all packages loaded, this happens because `Rays` is defined in Convex and `Div` is defined in RCWA:
```
########> Diff in /data/gap-jenkins/workspace/GAP-pkg-update-master-quicktest/\
GAPCOPTS/64build/GAPGMP/gmp/GAPTARGET/packages/label/kovacs/GAP-pkg-update-mas\
ter-snapshot/pkg/Toric-1.9.2/tst/examples.tst:113
# Input is:
Div:=[6,6,0];; Rays:=[[2,-1],[-1,2],[-1,-1]];;
# Expected output:
# But found:
Error, Variable: 'Div' is read only
Error, Variable: 'Rays' is read only
########
```
and obviously subsequent tests fail. This may be fixed by using different identifiers for variables in the test. I suggest to name them starting them in lowercase, this should allow to avoid name clashes as explained at http://gap-packages.github.io/example/doc/chapA.html#X7DEACD9786DE29F1:

> Additionally, there is a recommended naming convention that the GAP core system and GAP packages should not use global variables starting in the lowercase. This allows to reserve variables with names starting in lowecase to the GAP user so they will never clash with the system. It is extremely important to avoid using for package global variables very short names started in lowercase. For example, such names like cs, exp, ngens, pc, pow which are perfectly fine for local variables, should never be used for globals. Additionally, the package must not have writable global variables with very short names even if they are starting in uppercase, for example, C1 or ORB, since they also could be easily overwritten by the user.

**Comment by wdjoyner** [comment]
On Sat, Feb 4, 2017 at 8:30 PM, Alexander Konovalov <
notifications@github.com> wrote:

> With all packages loaded, this happens because Rays is defined in Convex
> and Div is defined in RCWA:
>
> ########> Diff in /data/gap-jenkins/workspace/GAP-pkg-update-master-quicktest/\
> GAPCOPTS/64build/GAPGMP/gmp/GAPTARGET/packages/label/kovacs/GAP-pkg-update-mas\
> ter-snapshot/pkg/Toric-1.9.2/tst/examples.tst:113
> # Input is:
> Div:=[6,6,0];; Rays:=[[2,-1],[-1,2],[-1,-1]];;
> # Expected output:
> # But found:
> Error, Variable: 'Div' is read only
> Error, Variable: 'Rays' is read only
> ########
>
> and obviously subsequent tests fail. This may be fixed by using different
> identifiers for variables in the test. I suggest to name them starting them
> in lowercase, this should allow to avoid name clashes as
>


The attached examples.tst file has the same commands but the offending
local variables are now in lower case. Can you please replace the old file
with this new one and retest?

explained at http://gap-packages.github.io/example/doc/chapA.html#

**Comment by fingolfin** [comment]
@wdjoyner I am afraid mail attachments are not transfered to the issue tracker, you'd have to attache them here manually.
But that's not necessary now, as I fixed the issue directly.

**Comment by wdjoyner** [comment]
On Mon, Feb 6, 2017 at 7:22 AM, Max Horn <notifications@github.com> wrote:

> @wdjoyner <https://github.com/wdjoyner> I am afraid mail attachments are
> not transfered to the issue tracker, you'd have to attache them here
> manually.
> But that's not necessary now, as I fixed the issue directly.
>

Thank you Max!
